data:
  train: /data/code/represent-code-in-human/data/code-summarization-enhanced-full/train_utf8.jsonl
  valid: /data/code/represent-code-in-human/data/code-summarization-enhanced-fullalid_utf8.jsonl
  test: /data/code/represent-code-in-human/data/code-summarization-enhanced-full/test_utf8.jsonl

tlc_data:
  train: /data/code/represent-code-in-human/data/TLC-SUM-enhanced/train.jsonl
  valid: /data/code/represent-code-in-human/data/TLC-SUM-enhancedalid.jsonl
  test: /data/code/represent-code-in-human/data/TLC-SUM-enhanced/test.jsonl

small_data:
  train: /data/code/represent-code-in-human/data/code-summarization-enhanced-small/train_utf8.jsonl
  valid: /data/code/represent-code-in-human/data/code-summarization-enhanced-smallalid_utf8.jsonl
  test: /data/code/represent-code-in-human/data/code-summarization-enhanced-small/test_utf8.jsonl

middle_data:
  train: /data/code/represent-code-in-human/data/code-summarization-enhanced-middle/train_utf8.jsonl
  valid: /data/code/represent-code-in-human/data/code-summarization-enhanced-middlealid_utf8.jsonl
  test: /data/code/represent-code-in-human/data/code-summarization-enhanced-middle/test_utf8.jsonl

ccd_data:
  data: /data/dataset/CodeXGLUE/Code-Code/Clone-detection-BigCloneBench/dataset/data.jsonl
  train: /data/dataset/CodeXGLUE/Code-Code/Clone-detection-BigCloneBench/dataset/train.txt
  valid: /data/dataset/CodeXGLUE/Code-Code/Clone-detection-BigCloneBench/dataset/test.txt
  test: /data/dataset/CodeXGLUE/Code-Code/Clone-detection-BigCloneBench/datasetalid.txt

ccd_f_data:
  data: /data/pycharm/BCB2015/BCB_F/function_out_split/data.jsonl
  train: /data/pycharm/BCB2015/BCB_F/function_out_split/train.txt
  valid: /data/pycharm/BCB2015/BCB_F/function_out_split/test.txt
  test: /data/pycharm/BCB2015/BCB_F/function_out_splitalid.txt

preprocess:
  max_source_length: 256
  max_target_length: 32

training:
  batch_size: 128
  num_epoches: 100
  lr: 0.001
  decay_ratio: 0.95
  save_name: /model.pth
  warm_up: 5
  patience: 10

model:
  graph_embedding_size: 768
  gnn_layers_num: 3
  lstm_layers_num: 2
  lstm_hidden_size: 768
  divide_node_num: 30
  decoder_input_size: 768
  decoder_hidden_size: 128
  decoder_num_layers: 2
  decoder_rnn_dropout: 0.5
  gine_dim: 128
  siamese_input_size: 768

logs:
  info_prefix: dgnn
